apiVersion: v1
kind: ConfigMap
metadata:
  name: happykube-bot-messages
data:
  MESSAGES_WELCOME: "Ciao! ðŸ˜Š Sono HappyKube! Dimmi come ti senti oggi!"
  MESSAGES_ASK_EMOTION: "Dimmi come ti senti, sono qui per ascoltarti!"
  MESSAGES_EXIT: "Bot in chiusura gentile. Grazie per aver usato HappyKube! ðŸ«¶"
  MESSAGES_NOT_IDENTIFIED: "Utente non identificato."
  MESSAGES_EMPTY: "Messaggio vuoto."
  MESSAGES_ERROR: "Errore durante l'analisi."
  MESSAGES_NOT_UNDERSTOOD: "Non ho capito l'emozione."
  MESSAGES_THANKS: "Grazie!"