apiVersion: v1
kind: ConfigMap
metadata:
  name: happykube-bot-messages
data:
  messages.ini: |
    [MESSAGES]
    welcome = Ciao! ðŸ˜Š Sono HappyKube! Dimmi come ti senti oggi!
    ask_emotion = Dimmi come ti senti, sono qui per ascoltarti!
    exit = Bot in chiusura gentile. Grazie per aver usato HappyKube! ðŸ«¶
    not_identified = Utente non identificato.
    empty = Messaggio vuoto.
    error = Errore durante l'analisi.
    not_understood = Non ho capito l'emozione.
    thanks = Grazie!